// Define variable
def S3_PATH = "s3://temp/"

// Declarative pipeline
pipeline {
  // agent any
  // This will install the python docker with version 3.7 to run build
  agent { docker { image 'python:3.7.2' } }
  stages {
    stage('build') {  // Build stage
      steps {
        sh 'virtualenv .venv' // Creating the virtual python environment
      }
    }
    stage('test') { // Test stage
      steps {
        sh """
             source .venv/bin/activate
           """ // Activation of python virtual environment
      }
      post {
        always {
          junit 'test-reports/*.xml' // Generating the test report
        }
      }
    }
    stage('deploy') { // Deploy stage
      steps {
        sh """
            aws s3 cp dist/my_application-*.whl ${S3_PATH} /
           """ // Uploading binary to s3
      }
    }
  }
}