// Defining constant global variables
def S3_PATH = "s3://test-ankur-1/users/temp/"

// Pipeline definition
pipeline {
  agent any
  stages {
  // build stage
    stage('build') {
      steps {
        sh 'virtualenv .venv' // Creating the python virtual environment
        // Running python setup tool to create wheel distribution file
        sh """
            source .venv/bin/activate
            pip install -r Labs/usecases/usecase-1/requirements.txt
            pip install wheel
            python Labs/usecases/usecase-1/setup.py bdist_wheel
           """
      }
    }
  // test stage
    stage('test') {
      steps {
        // Running the test suits present in code
        sh """
             source .venv/bin/activate
             python Labs/usecases/usecase-1/my_application/test.py
           """
      }
      // Generating test reports
      post {
        always {
          junit 'test-reports/*.xml'
        }
      }
    }
    // Stage to upload binary to s3
    // Deactivating python virtual environment
    stage('uploadBinaryToS3') {
      steps {
        sh """
              source .venv/bin/activate
              ls dist/Labs/usecases/usecase-1/
              aws s3 cp dist/Labs/usecases/usecase-1/my_application-*.whl ${S3_PATH}
              source deactivate
           """
      }
    }
    //Deploy stage
    stage('deploy') {
       // Running terraform scripts and uploading plan file to s3
      steps {
        sh """
              terraform -v
              cd Labs/usecases/usecase-1terraform
              terraform init
              terraform plan -out plan.out
              terraform apply -auto-approve plan.out
              terraform plan -destroy -out planfile
              aws s3 cp plan.out ${S3_PATH}/terraform
              aws s3 cp planfile ${S3_PATH}/terraform
           """
      }
    }
  }
  // Stage to clean up workspace
  post {
        always {
            cleanWs()
        }
    }
}